# -*- coding: utf-8 -*-
"""Classification Mobile Price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttWyCSZazAR4RGoJE3xiK7sF_u92r05t

# Mobile Price Classification

### Objetivo del proyecto:

El objetivo de este proyecto es crear un clasificador de precios de teléfonos móviles en función de sus diferentes características técnicas (RAM, batería, cámara, almacenamiento, etc.). Usaremos el dataset Mobile Price Classification de Kaggle, el cual contiene múltiples atributos de hardware y una etiqueta que clasifica cada móvil en una de cuatro categorías de precio:

https://www.kaggle.com/datasets/iabhishekofficial/mobile-price-classification
"""



"""### Dataset:

- ID: ID del producte (valor enter)

- Battery_power: total d’energia que pot emmagatzemar la bateria (mAh) (valor enter)

- Blue: si té bluetooth (valor booleà: 0 = no, 1 = sí)

- Clock_speed: velocitat del microprocessador en GHz (valor decimal)

- Dual_sim: si té suport per a doble SIM (valor booleà: 0 = no, 1 = sí)

- Fc: resolució de la càmera frontal en megapíxels (valor enter)

- Fourth_gen: si suporta 4G (valor booleà: 0 = no, 1 = sí)

- Int_memory: memòria interna en GB (valor enter)

- M_dep: profunditat del mòbil en centímetres (valor decimal)

- Mobile_wt: pes del mòbil en grams (valor enter)

- N_cores: nombre de nuclis del processador (valor enter)

- Pc: resolució de la càmera posterior en megapíxels (valor enter)

- Px_height: alçada de la resolució de pantalla en píxels (valor enter)

- Px_width: amplada de la resolució de pantalla en píxels (valor enter)

- Ram: memòria RAM del dispositiu en MB (valor enter)

- Sc_h: alçada de la pantalla en polzades (valor enter)

- Sc_w: amplada de la pantalla en polzades (valor enter)

- Talk_time: autonomia de trucada màxima (hores) (valor enter)

- Three_g: si suporta 3G (valor booleà: 0 = no, 1 = sí)

- Touch_screen: si té pantalla tàctil (valor booleà: 0 = no, 1 = sí)

- Wifi: si té connexió WiFi (valor booleà: 0 = no, 1 = sí)

- Price_range: categoria de preu (0 = baix, 1 = mitjà, 2 = alt, 3 = molt alt)
"""